version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Puerto externo 3000 mapeado al puerto 80 interno
    container_name: sistema-gestion-frontend
    restart: unless-stopped
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Solo lectura
    networks:
      - app-network

networks:
  app-network:
    driver: bridge