CREATE TABLE "User" (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(255) NOT NULL,
    Code NVARCHAR(100) NOT NULL,
    Active BIT NOT NULL DEFAULT 1,
    CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
    DeleteAt DATETIME NULL,
    PersonId INT NOT NULL,
    CONSTRAINT FK_User_Person FOREIGN KEY (PersonId) REFERENCES Person(Id)
);


CREATE TABLE Person (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) UNIQUE NOT NULL
);


CREATE TABLE Rol (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Active BIT NOT NULL DEFAULT 1,
    CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
    DeleteAt DATETIME NULL
);


CREATE TABLE RolUser (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL,
    RolId INT NOT NULL,
    CONSTRAINT FK_RolUser_User FOREIGN KEY (UserId) REFERENCES [User](Id),
    CONSTRAINT FK_RolUser_Rol FOREIGN KEY (RolId) REFERENCES Rol(Id)
);

CREATE TABLE Module (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Active BIT NOT NULL DEFAULT 1,
    CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
    DeleteAt DATETIME NULL
);


CREATE TABLE Form (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Code NVARCHAR(100) NOT NULL,
    Active BIT NOT NULL DEFAULT 1,
    CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
    DeleteAt DATETIME NULL
);


CREATE TABLE FormModule (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ModuleId INT NOT NULL,
    FormId INT NOT NULL,
    CONSTRAINT FK_FormModule_Module FOREIGN KEY (ModuleId) REFERENCES Module(Id),
    CONSTRAINT FK_FormModule_Form FOREIGN KEY (FormId) REFERENCES Form(Id)
);


CREATE TABLE Permission (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Active BIT NOT NULL DEFAULT 1,
    Code NVARCHAR(100) NOT NULL,
    CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
    DeleteAt DATETIME NULL
);


CREATE TABLE RolFormPermission (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    RolId INT NOT NULL,
    PermissionId INT NOT NULL,
    FormId INT NOT NULL,
    CONSTRAINT FK_RolFormPermission_Rol FOREIGN KEY (RolId) REFERENCES Rol(Id),
    CONSTRAINT FK_RolFormPermission_Permission FOREIGN KEY (PermissionId) REFERENCES Permission(Id),
    CONSTRAINT FK_RolFormPermission_Form FOREIGN KEY (FormId) REFERENCES Form(Id)
);


CREATE TABLE ChangeLog (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    TableId INT NOT NULL,
    UserId INT NOT NULL,
    Date DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_ChangeLog_User FOREIGN KEY (UserId) REFERENCES [User](Id)
);

